apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: roundcube-identity-switch-config
    namespace: apps
    files:
      - ./config/identity_switch_config.php
generatorOptions:
  disableNameSuffixHash: true
