# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.3.0/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/autobrr/qui
          tag: v1.13.1@sha256:ab5626ffb9177dd90c33113e5a1b7a8677daee2306de8f5cc35f10e85ea7a72b
        envFrom:
          - secretRef:
              name: qui

defaultPodOptions:
  annotations:
    reloader.stakater.com/auto: "true"

service:
  main:
    controller: main
    ports:
      http:
        port: 7476

persistence:
  config:
    enabled: true
    existingClaim: qui-data
    globalMounts:
      - path: /config

ingress:
  main:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/funnel: "true"
      tailscale.com/hostname: qui
    hosts:
      - host: qui.${TAILSCALE_DOMAIN}
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - qui.${TAILSCALE_DOMAIN}
